### ISSUE TITLE
API不太友好

### ISSUE THREAD

**Issue by xujinyang** [Jomes/routerSDK#2]
最好能设计成复合Web规范的URI，还有统一注册，不如在每个页面自己注册

**Comment by Jomes** [comment]
最好能设计成复合Web规范的URI
----》
这个是兼容web 的格式的 比如http://www.androidblog.cn/?name=Tom&id=1 ，这个参数就变成了默认的String 类型。

统一注册，不如在每个页面自己注册
---》
可以做成动态配置路由表的
